r8format/Functest: Only functional tests now; Test calls this
The top-level Test has always been running all the unit tests in this repo,
including the t8dev and r8format subdirs. We now rely on that.

r8format/Test is moved to r8format/Functest and its unit-testing
functionality is removed. The top-level Test script calls it when the unit
tests are complete and pass.

r8format/Functest still calls r8format/psrc/cmtconv/Test, which does the
functional tests for cmtconv. That now assumes (with a check) that
$T8_PROJDIR is set (so it knows where to put files generated by the tests)
and that the virtualenv with cmtconv is already set up, rather than setting
up its own.

r8format/requirements.txt is removed because now the only virtual
environment we use is at the root, it already brings in `pytest` and
`pytest_pt` as package dependencies, and `build` and `twine` are now
brought in independently by [cynic-net/pypi-release] when we need
to do a release.

diff --git a/r8format/Functest b/r8format/Functest
--- a/r8format/Functest
+++ b/r8format/Functest
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
+#
+#   This is expected to be called from ../Test.
+#   It assumes that the virtualenv with r8format is activated.
+#
 set -eu -o pipefail
+trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
+      exit $ec;' ERR
 
 PASSED=false
 trap 'ec=$?; $PASSED || { echo 1>&2 "*** FAILED (exitcode=$ec)"; }' 0
@@ -16,34 +22,25 @@ hexdiff() {
         <(xxd -c8 -g1 "$1") <(xxd -c8 -g1 "$2")
 }
 
+####################################################################
+
+[[ -d ${T8_PROJDIR:-} ]] || { echo 2>&1 \
+    '$T8_PROJDIR not set; not called from top-level Test?'; exit 7; }
 basedir=$(cd "$(dirname "$0")" && pwd -P)
 cd "$basedir"
 
-#   -C/-c (clean) must be first argument if present
-[[ ${#@} -gt 0 && $1 == -C ]] && { shift; rm -rf .build/; }
-[[ ${#@} -gt 0 && $1 == -c ]] && { shift; rm -rf .build/; }
 #   -q anywhere in the command line (even with -v!) sets functests quiet.
 quiet=
 for arg in "$@"; do [[ $arg == -q ]] && quiet=-q; done
 
-. ./pactivate -q
-pip show r8format 2>/dev/null \
-    | grep -s 'Editable project location:' >/dev/null \
-|| {
-    echo "Installing editable r8format..."
-    pip install -q -e .
-}
-
 
 ####################################################################
-#   Unit Tests
-
-pytest -q "$@"      # use pyproject.toml for configuration
+#   Unit tests have already been done by ../Test.
 
 ####################################################################
 #   Functional Tests
 
-ftdata=.build/programs/
+ftdata=$T8_PROJDIR/.build/programs/
 mkdir -p $ftdata/detok
 
 echo "====== bastok"
diff --git a/r8format/psrc/cmtconv/Test b/r8format/psrc/cmtconv/Test
--- a/r8format/psrc/cmtconv/Test
+++ b/r8format/psrc/cmtconv/Test
@@ -9,9 +9,16 @@
 #   That output is often just the exit code; you need to test that to
 #   see if it passed or failed. E.g., `./cmt-test; echo EXITCODE $?`
 #
-
-set -eu -o pipefail
+set -Eeuo pipefail
 ulimit -v $((3*1024*1024))
+
+#   We're now expected to be called with an already-set-up T8_PROJDIR and
+#   virtualenv. Eventually this should all be moved up into the top-level
+#   test framework, perhaps as pytest tests.
+[[ -d ${T8_PROJDIR:-} ]] || { echo 2>&1 \
+    '$T8_PROJDIR not set; not called from top-level Test?'; exit 7; }
+cmtconv -h >/dev/null || {
+    echo 1>&2 'cmtconv not found; virtualenv activated?'; exit 7; }
 
 die() { echo 2>&1 FAILURE: "$@"; exit 1; }
 qecho() { [[ -n $quiet ]] && return; echo "$@"; }
@@ -159,9 +166,7 @@ while [[ ${#@} -gt 0 ]]; do case "$1" in
     *)      die "Bad arg to Test: $1";;
 esac; done
 
-. "$projdir"/pactivate -q -B "$projdir"
-
-ttdir="$projdir/.build/cmtconv-test"
+ttdir="$T8_PROJDIR/.build/cmtconv-test"
 #   We remove all temporary files and results from previous runs to avoid
 #   potentially false test results or developer confusion when debugging.
 rm -rf "$ttdir"; mkdir -p "$ttdir"
